import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";

import { Breadcrumbs } from "~/components/breadcrumbs";
import { JsonLd } from "~/components/json-ld";
import { PawMark } from "~/components/paw-mark";
import { Container, CtaLink, FaqList, Heading, Section } from "~/components/ui";
import { getService, services } from "~/lib/content";
import { pageMetadata } from "~/lib/metadata";
import { absoluteUrl, APP_URL, backoffice } from "~/lib/site";
import { breadcrumbSchema, faqSchema, serviceSchema } from "~/lib/structured-data";

import type { Metadata } from "next";

type Props = { params: Promise<{ slug: string }> };

/**
 * One statically rendered page per service.
 *
 * `generateStaticParams` with `dynamicParams = false` means the six routes are
 * built as HTML at build time and anything else is a 404 — no server render, no
 * chance of a crawler finding an infinite space of `/servicos/<anything>` URLs
 * that all return 200 and dilute the site.
 */
export const dynamicParams = false;

export function generateStaticParams() {
  return services.map((service) => ({ slug: service.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const service = getService(slug);

  if (!service) return {};

  return pageMetadata({
    title: service.heading,
    description: service.metaDescription,
    path: `/servicos/${service.slug}`,
    keywords: service.keywords,
    // The per-service card generated by the sibling opengraph-image route, not
    // the service photo: those photos are portrait, and every social platform
    // crops share images to about 1.91:1.
    image: absoluteUrl(`/servicos/${service.slug}/opengraph-image`),
  });
}

export default async function ServicePage({ params }: Props) {
  const { slug } = await params;
  const service = getService(slug);

  if (!service) notFound();

  const trail = [
    { name: "Início", path: "/" },
    { name: "Serviços", path: "/servicos" },
    { name: service.name, path: `/servicos/${service.slug}` },
  ];

  const related = services.filter((item) => item.slug !== service.slug).slice(0, 3);

  return (
    <>
      <JsonLd schema={[breadcrumbSchema(trail), serviceSchema(service), faqSchema(service.faq)]} />

      <Section className="from-brand-wash bg-gradient-to-b to-white pb-10">
        <Container>
          <Breadcrumbs trail={trail} />

          <div className="mt-8 grid items-center gap-10 lg:grid-cols-[1.1fr_1fr]">
            <div>
              <Heading as="h1" eyebrow={service.name}>
                {service.heading}
              </Heading>
              <p className="text-ink-soft mt-5 max-w-xl text-lg leading-relaxed">{service.intro}</p>

              <div className="mt-8 flex flex-wrap gap-3">
                <CtaLink href={APP_URL} external variant="primary">
                  Encontrar no app
                </CtaLink>
                <CtaLink href="/servicos" variant="ghost">
                  Ver todos os serviços
                </CtaLink>
              </div>
            </div>

            <div className="rounded-card overflow-hidden">
              <Image
                src={service.image}
                alt={service.imageAlt}
                placeholder="blur"
                priority
                sizes="(min-width: 1024px) 42vw, 92vw"
                className="h-full w-full object-cover"
              />
            </div>
          </div>
        </Container>
      </Section>

      <Section className="bg-white pt-6">
        <Container className="max-w-4xl">
          <h2 className="text-ink font-display text-2xl font-semibold sm:text-3xl">
            O que está incluído
          </h2>
          <ul className="mt-6 grid gap-4 sm:grid-cols-2">
            {service.includes.map((item) => (
              <li
                key={item}
                className="border-line rounded-card flex items-start gap-3 border bg-white p-5"
              >
                <PawMark className="mt-0.5 w-5 shrink-0" />
                <span className="text-ink-soft leading-relaxed">{item}</span>
              </li>
            ))}
          </ul>
        </Container>
      </Section>

      <Section className="bg-sky-band/40">
        <Container className="max-w-4xl">
          <Heading>Perguntas frequentes sobre {service.name.toLowerCase()}</Heading>
          <div className="mt-8">
            <FaqList entries={service.faq} />
          </div>
        </Container>
      </Section>

      {/* The provider half of the same keyword: someone searching "pet sitter"
          may well be looking to become one. */}
      <Section className="bg-cream">
        <Container className="max-w-4xl">
          <h2 className="text-ink font-display text-2xl font-semibold sm:text-3xl">
            Você oferece {service.name.toLowerCase()}?
          </h2>
          <p className="text-ink-soft mt-3 max-w-2xl leading-relaxed">
            Cadastre seu negócio na rede Animalesko e apareça para os tutores da sua região. A
            gestão de agenda, clientes e faturamento fica no back office, em{" "}
            <span className="font-medium">{backoffice.hostname}</span>
            {backoffice.isLive ? "." : " — que entra no ar em breve."}
          </p>
          <div className="mt-6">
            <CtaLink
              href={backoffice.isLive ? backoffice.href! : "/para-prestadores"}
              external={backoffice.isLive}
              variant="accent"
            >
              {backoffice.isLive ? "Entrar no back office" : "Quero ser parceiro"}
            </CtaLink>
          </div>
        </Container>
      </Section>

      <Section className="bg-white">
        <Container>
          <h2 className="text-ink font-display text-2xl font-semibold sm:text-3xl">
            Outros serviços
          </h2>
          <ul className="mt-8 grid gap-6 sm:grid-cols-3">
            {related.map((item) => (
              <li key={item.slug}>
                <Link
                  href={`/servicos/${item.slug}`}
                  className="group border-line hover:border-brand rounded-card flex h-full flex-col border p-6 transition-colors"
                >
                  <h3 className="text-ink group-hover:text-brand font-display text-lg font-semibold transition-colors">
                    {item.name}
                  </h3>
                  <p className="text-ink-soft mt-2 text-sm leading-relaxed">{item.summary}</p>
                </Link>
              </li>
            ))}
          </ul>
        </Container>
      </Section>
    </>
  );
}
